name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Add $GOPATH/bin to $PATH
        run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1

      - name: Format
        run: diff <(echo -n) <(gofmt -s -d .)

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: Run staticcheck
        run: staticcheck ./...
